### ISSUE TITLE
"Go语言路线和资源征集(update 2023)" invalid in readme

### ISSUE THREAD

**Issue by suisbuds** [cubxxw/awesome-cs-cloudnative-blockchain#47]
**Describe the bug**
The link called "Go语言路线和资源征集(update 2023)" is **invalid** that points to 404 in readme

**To Reproduce**
1. Go to '[awesome-cs-cloudnative-blockchain](https://github.com/cubxxw/awesome-cs-cloudnative-blockchain)'
2. Click on 'Go语言路线和资源征集(update 2023)' link
3. See error

**Expected behavior**
This link should point to sth, and it's valid in branch **main** while invalid in current branch **master**

**Additional context**
Maybe move the valid link from main branch to master branch?

**Comment by cubxxw** [comment]
谢谢你的建议，已经修复 ！
